### PR TITLE
Use Tooltip scanning for looking into enemy buffs

### LINKED ISSUE #33: Buff icon and tooltip showing different buff
Saw a https://classic.wowhead.com/icon=134153 icon on mage with 2h duration and mouseover said its arcane intellect.
friend of mine saw https://classic.wowhead.com/icon=132219 on rogue and tooltip said its elixir of mongoose, not sure what timer it had,
Im using elvui and my friend has ClassicAuraDurations so i figured it must be problem with the lib

Happened again and managet to get screenshots this time
https://puu.sh/EAQbp/0ea078df82.png

https://puu.sh/EAQfS/00bd66f917.png
https://puu.sh/EAQgJ/588bca76d9.png
https://puu.sh/EAQgs/5c50fe3feb.png
in last shot you can see the first buff not dissappearing after timer runs out too
and the mage had atleast Ice Barrier on for sure

### PR DESCRIPTION
**Pull request by Aviana**
This might fix #33

### CODE REVIEW

**Comment by d87** [comment]
if we're scanning tooltips, then it should use it as the main source rather than plugging it after the old method. So generate buffs table from tooltips and fill duration at the same time from CL data.

(It's probably not an issue with custom unitframes, but CAD is already causing 'Script ran too long' errors sometimes  with enemy buffs enabled, so i'm a little afraid to make it any slower)

The drawback is that the fallback won't work if blizzard fixes it. But i suspect they're past the point of caring.

**Comment by d87** [comment]
So i switched to that in the latest commit. Could you confirm that everything still works? I don't have a sub currently and ptr is down

**Comment by Aviana** [comment]
I did some testing in AV and everything seems to be in order. The biggest "downside" is that there are now unknown buffs that utilize the samwise icon because i only have the name of the buff und not a spellID. Thats also why i added some more data.

**Comment by d87** [comment]
Oh right, skipping those now

**Comment by Aviana** [comment]
If you want to test you can add me on bnet and i'll gift you a month ;D

**Comment by Aviana** [comment]
CptAwesome#2205 on bnet europe.

**Comment by d87** [comment]
Well, i believe you if you say it's fine. But alright

**Pull request merged**
